name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # 必要なNodeのバージョンを指定

    - name: Install dependencies
      run: npm ci  # lockfileを使って確実に再現可能な依存解決

    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: latest
    
    - name: Run Biome
      run: npx biome check --write

    - name: Build Project
      run: npm run build

  upload-images:
        runs-on: ubuntu-latest
        needs: build  # buildジョブが成功したら実行
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Install rclone
            run: |
              curl https://rclone.org/install.sh | sudo bash

          - name: Configure rclone
            run: |
              mkdir -p ~/.config/rclone
              echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

          - name: Upload to R2
            run: |
              rclone sync src/content/assets r2:nababa-blog/assets